model:
  learning_rate: 4.5e-06
  target: models_vq.VQModel
  params:
    embed_dim: 4
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 100
      in_channels: 80
      out_ch: 80
      ch: 128
      ch_mult:
      - 1
      - 1
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.0